server:
  port: 9001

spring:
  profiles:
    active: nonprod
---
spring:
  profiles:
    default: nonprod
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: nonprod
