spring:
  profiles:
    active: nonprod
server:
  port: 8090
---
spring:
  datasource:
    url: jdbc:oracle:thin:@34.87.9.238:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: system123
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle8iDialect
    generate-ddl: true
  config:
    activate:
      on-profile: nonprod
